name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Modpack Version Used
      description: Which numerical version of the modpack are you using?
      placeholder: 1.0.0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "I was too awesome and it broke the game."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant latest.log
      description: Please copy and paste your latest.log, or a gist.github.com link to the log contents. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: crash
    attributes:
      label: Relevant crash report
      description: Please copy and paste your relevant crash report, or a gist.github.com link to the report contents. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true