name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Modpack Version Used
      description: Which numerical version of the modpack are you using? Ex - 1.4.3
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "I was too awesome and it broke the game."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Your logs folder is located in your base Minecraft directory./nAssuming you're using Curseforge Client - In the Cottage Witch page, find the 3 dots next to the Play button, and click "Open Folder."/nThen go to the "/logs/" folder and take the "latest.log" and/or "debug.log" and drag it into discord chat or upload it to gist.github.com.
  - type: textarea
    id: logs
    attributes:
      label: Relevant latest.log
      description: Please copy and paste your latest.log, or a gist.github.com link to the log contents. This will be automatically formatted into code, so no need for backticks.
  - type: textarea
    id: crash
    attributes:
      label: Relevant crash report
      description: Please copy and paste your relevant crash report, or a gist.github.com link to the report contents. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true