
["NBT Tags"]
	#Show mod name in tooltip.  Default: false
	showModName = true
	#Show nbt length, in bytes, in the tooltip.  Default: true
	showNBTLength = false
	#Show NBT and Tags only if Advanced Tooltips (F3 + h) is on.  Default: true
	showAsAdvanced = true

["Clock Time Format"]
	#Show 12 or 24 hour clock format.  Default: false
	#true for 12 hour, false for 24 hour
	isTwelves = true

